### ISSUE TITLE
Make sure title is part of field when I am using --export flag

### ISSUE THREAD

**Issue by sidharthshah** [yspanchal/bitbucketcli#11]
When exporting the header of excel file only contains 

ID,Status,Kind,Priority,Version,Component,Milestone,Reported By,Created On,Last Updated,Responsible,Comment Count,is_spam,Followers Count

We need title field.

**Comment by yspanchal** [comment]
Issue Fixed added title in csv export commit id: e33bea5254a05218663a251af2cc6d6f8211607e
