### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by dilawar** [yspanchal/bitbucketcli#12]
I am using `Python 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC] on linux2`

```
bitbucket login
Login to Your BitBucket Account.

Enter BitBucket Username or Email [dilawars]:dilawar
Enter Password: 
Enter Password (Again): 
'Extensions' object has no attribute 'get_extension_for_class'
```

**Comment by chaps** [comment]
Are you still having this issue?

**Comment by dilawar** [comment]
I am using with python3. I have made some changes on my fork. I could login and see the available command. However, python3 dict does not have `viewkeys` attribute, and it is causing errors in few command.

**Comment by chaps** [comment]
Alright , I will check it out. 
Thanks for the response.

**Comment by chaps** [comment]
@dilawar got your issue on the repo create command , I'm working on a python3 port and will create another issue regarding that AttributeError when working over python3 under that specific command.

**Comment by chaps** [comment]
https://github.com/yspanchal/bitbucketcli/pull/24 solves Python3 port,
along with viewkeys viewvalues attribute errors.

**Comment by yspanchal** [comment]
#24 solves
