### ISSUE TITLE
'user' not defined when calling a command before setting up the credentials file/ logging in.

### ISSUE THREAD

**Issue by chaps** [yspanchal/bitbucketcli#17]
When calling any command from the cli (except login or logout ) like `bitbucket repo list` before calling `bitbucket login` or just `bitbucket` to setup the account's credentials there will be a raised NameError exception "user is not defined".

The program will load the module containing the issued command and will try to load the user and passwd variables before being able to call the auth method from BitBucketApp at main.py and setting up the file with the credentials which afterwards when calling the command corresponding class will try to used the user and passwd variables that should had been setup before and thus raising the error.

##Reproduce:
- Remove the credentials file if set. (`rm ~/.bitbucket.py`)
- Call any command (`bitbucket repo list`)
- Follow up the account's setup.
- If setup/login successfully an issue will be raised afterwards when issuing the requested command.

**Comment by yspanchal** [comment]
7034aff merged
