### ISSUE TITLE
Missleading error message for 403, 404 (repo deploykey-list)

### ISSUE THREAD

**Issue by vlcinsky** [yspanchal/bitbucketcli#3]
Trying to list deployment keys, sometime I get misleading error messages:

    $ bitbucket repo deploykey-list -a someaccount -r somerepo
    Error: "403" Invalid request, Invalid Account name "someaccount" or Repository Name "somerepo"

and sometime it looks different:

    $ bitbucket repo deploykey-list -a someaccount -r somerepowithtypo
    Error: "404" Invalid request, Invalid Account name "someaccount" or Repository Name "somerepo"

The problem is, that the message looks like I have invalid account name or repository name, but in some cases they are correct but do not allow me to do the action (notice the difference in 403 and 404).

Proposed changes:

## Change wording

Change the message to something not talking that account or repository is necessarily invalid:

    '\n Error: "{r.status_code}" for Account name "{parsed_args.account}" and/or Repository Name "{parsed_args.reponame}"\n\n'

## Try to show error text from the HTTP response

There few sources related to the response which can provide more explanatory message:

1. if response body is JSON and has "error.message" property, use that (this is e.g. case of non-existent repository)
2. if response is plain text, use the first line (or some other limited number of lines) (this is e.g. case of repository not providing access to given information shown by a line "Forbidden".
3. otherwise provide standardized name for given HTTP status code.

Such a message could be added to the error message as follows:

    '\n Error: code: "{r.status_code}", message: {errmessage} for Account name "{parsed_args.account}" and/or Repository Name "{parsed_args.reponame}"\n\n'

**Comment by yspanchal** [comment]
@vlcinsky pull requests merged 37e365c0938f3455a3c3efb9345c49d3d0d26a1d

Thank you.
