### ISSUE TITLE
Reformat the code to be more PEP008 compliant

### ISSUE THREAD

**Issue by vlcinsky** [yspanchal/bitbucketcli#5]
Existing code does not fulfil many of PEP008 recommendations like:

- for code formatting use space instead of tabs
- max line length 79 characters
- (more can come out when tested by pylint end similar tools)

@yspanchal If you agree, I can do this reformatting (I do not want to spend time on it, if it would not be used).

**Comment by yspanchal** [comment]
@vlcinsky If you can do this, Please do it. But i think priority would be writting test.

**Comment by vlcinsky** [comment]
@yspanchal happy to see your agreement.
I will do this first as it shall serve as good base for any following modifications.

My tox and testing modifications are partially done, but having some troubles, so I will deal with completing tests after PEP008 reformatting.
