### ISSUE TITLE
Add initial test suite and use tox

### ISSUE THREAD

**Issue by vlcinsky** [yspanchal/bitbucketcli#8]
Test suite shall speed up modifications.

Using `tox` shall speed up testing, if the distribution is really complete and runs well under different python versions.

However, as it interacts with external resource (bitbucket), we cannot easily test access to private repositories as we would have to include credentials for some account.

For this reason, initial test suite would test only interaction with public repositories, which do not require privete repository credentials.

**Comment by vlcinsky** [comment]
It seems like the `bitbucket` command assumes, user must be logged in. This seems logical but prevents publicly available test suite, as someone would have to provide credentials to a bitbucket account.

For this reason I would aim at tox being run only on local machine (assuming there is already a `~/.bitbucket.py` file present).

This would speed up local development, but is not suitable for automated tests on public server.

**Comment by yspanchal** [comment]
@vlcinsky you can write tests and send me pull request. i'll merge it.

**Comment by vlcinsky** [comment]
@yspanchal Initial test suite created, but has couple of issues.

Anyway, after completing `PEP008` I must admit the test suite would help validating the refactored code (you were right with the priorities).

Anyway, number of issues with test suite was rather repelling my effort to start with that.

**Comment by vlcinsky** [comment]
Pull request #10 relates to this issue, but requires some decisions to be made.

**Comment by yspanchal** [comment]
@vlcinsky if you want to discuss something my gmail id is yspanchal@gmail.com
